import os
import re

NAME_SIGNALS = {
    'main': 'entry_point', 'index': 'entry_point', 'app': 'entry_point', 'apps': 'entry_point', 'cli': 'entry_point',
    'core': 'core_logic', 'scanner': 'core_logic', 'frameworks': 'core_logic',
    'prioritization': 'core_logic', 'llm': 'core_logic',
    'database': 'data_layer', 'db': 'data_layer', 'models': 'data_layer', 'model': 'data_layer',
    'utils': 'helper', 'util': 'helper', 'helpers': 'helper', 'helper': 'helper',
    'config': 'config', 'configs': 'config', 'configuration': 'config',
    'test': 'test', 'tests': 'test',
    'router': 'routing', 'routers': 'routing', 'routes': 'routing', 'route': 'routing',
    'api': 'api_layer', 'apis': 'api_layer',
}
GENERATED_PATH_MARKERS = ['migrations', 'dist', 'build', '.min.', '__generated__', 'generated', 'vendor']
GENERATED_CONTENT_MARKERS = ['auto-generated', 'do not edit', '@generated', 'generated by']

MIN_LINES_FOR_LLM = 5

CHEAP_TEMPLATES = {
    'helper': "Вспомогательный модуль с утилитарными функциями.",
    'test': "Файл с тестами для проверки корректности кода.",
    'config': "Конфигурационный файл проекта.",
    'routing': "Модуль маршрутизации/роутинга запросов.",
    'data_layer': None,  # data_layer always goes to LLM
}

def is_likely_generated(file_path: str, content: str) -> bool:
    """
    Checks if a file is likely auto-generated based on its path, headers, or lines density.
    """
    normalized_path = file_path.replace('\\', '/')
    if any(marker in normalized_path for marker in GENERATED_PATH_MARKERS):
        return True
        
    first_lines = '\n'.join(content.splitlines()[:3]).lower()
    if any(marker in first_lines for marker in GENERATED_CONTENT_MARKERS):
        return True
        
    lines = [l for l in content.splitlines() if l.strip()]
    if lines and (sum(len(l) for l in lines) / len(lines)) > 300:
        return True
        
    return False


def get_tokens(name_without_ext: str) -> list:
    """
    Splits the segment name by delimiters _ and - and camelCase into tokens.
    """
    words = re.split(r'[_|-]', name_without_ext)
    split_words = []
    for w in words:
        split_words.extend(re.sub(r'([a-z0-9])([A-Z])', r'\1 \2', w).lower().split())
    return split_words


def get_file_role(file_path: str) -> str:
    """
    Determines the semantic role of a file based on its name and path segments.
    """
    ROLE_PRIORITY = {
        'test': 10,
        'config': 9,
        'routing': 8,
        'data_layer': 7,
        'api_layer': 6,
        'helper': 5,
        'core_logic': 4,
        'entry_point': 3,
    }
    
    normalized = file_path.replace('\\', '/')
    segments = normalized.split('/')
    
    matched_roles = []
    
    for segment in segments:
        if not segment:
            continue
        # Strip extension if it's the last segment
        if segment == segments[-1]:
            name_without_ext = os.path.splitext(segment)[0]
        else:
            name_without_ext = segment
            
        tokens = get_tokens(name_without_ext)
        for token in tokens:
            if token in NAME_SIGNALS:
                matched_roles.append(NAME_SIGNALS[token])
                
    if not matched_roles:
        return None
        
    # Return the role with the highest priority
    return max(matched_roles, key=lambda r: ROLE_PRIORITY.get(r, 0))


def get_cheap_description(file_role: str, file_name: str, lines: int = None, content: str = None) -> str:
    """
    Returns a predefined summary for cheap/heuristic modules.
    For very short files, return the literal file content.
    """
    if lines is not None and content is not None and lines < MIN_LINES_FOR_LLM:
        snippet = content.replace('\r\n', '\n').strip()
        if not snippet:
            snippet = '(пустой файл)'
        return f"Короткий файл ({lines} строк): {snippet}"

    template = CHEAP_TEMPLATES.get(file_role)
    if template is None:
        return f"Файл {file_name} (роль не определена однозначно)."
    return template


def build_import_graph(files_metadata):
    """
    Walks all parsed files and builds an import graph counting references to other files.
    """
    import_counts = {f['rel_path']: 0 for f in files_metadata if f['ext'] != '.md'}
    
    # Map normalized paths to the actual rel_path
    path_to_rel = {}
    for f in files_metadata:
        rel = f['rel_path'].replace('\\', '/')
        path_to_rel[rel] = f['rel_path']
        base, ext = os.path.splitext(rel)
        path_to_rel[base] = f['rel_path']
        if ext == '.py':
            dotted = base.replace('/', '.')
            path_to_rel[dotted] = f['rel_path']
            
    for f in files_metadata:
        content = f['content']
        rel_path = f['rel_path'].replace('\\', '/')
        ext = f['ext']
        dir_name = os.path.dirname(rel_path)
        
        imported_modules = []
        if ext == '.py':
            # Extract standard python imports (use [ \t] instead of \s to prevent multiline matching)
            for m in re.finditer(r'^\s*import\s+([a-zA-Z0-9_\., \t]+)', content, re.MULTILINE):
                for module_part in m.group(1).split(','):
                    imported_modules.append(module_part.strip())
            for m in re.finditer(r'^\s*from\s+([a-zA-Z0-9_\.]+)\s+import', content, re.MULTILINE):
                imported_modules.append(m.group(1).strip())
        elif ext in ('.js', '.jsx', '.ts', '.tsx'):
            # Extract JS/TS imports and requires
            for m in re.finditer(r'import\s+.*\s+from\s+[\'"]([^\'"]+)[\'"]', content):
                imported_modules.append(m.group(1))
            for m in re.finditer(r'require\s*\(\s*[\'"]([^\'"]+)[\'"]\s*\)', content):
                imported_modules.append(m.group(1))
                
        for imp in imported_modules:
            if imp.startswith('.'):
                target_path = os.path.normpath(os.path.join(dir_name, imp)).replace('\\', '/')
                for ext_try in ('', '.ts', '.tsx', '.js', '.jsx', '/index.ts', '/index.tsx', '/index.js'):
                    resolved = target_path + ext_try
                    resolved = os.path.normpath(resolved).replace('\\', '/')
                    if resolved in path_to_rel:
                        import_counts[path_to_rel[resolved]] += 1
                        break
            else:
                resolved_file = None
                if imp in path_to_rel:
                    resolved_file = path_to_rel[imp]
                else:
                    slashed = imp.replace('.', '/')
                    for key in path_to_rel:
                        if key.endswith(slashed):
                            resolved_file = path_to_rel[key]
                            break
                if resolved_file:
                    import_counts[resolved_file] += 1
                    
    return import_counts


def calculate_importance_scores(files_metadata, import_graph):
    """
    Computes importance scores for all files.
    """
    scores = {}
    for f in files_metadata:
        rel_path = f['rel_path']
        if f['ext'] == '.md':
            scores[rel_path] = 0
            continue
        content = f['content']
        role = get_file_role(rel_path)
        
        score = 0
        score += f['lines'] * 0.3
        score += f['declarations'] * 2
        score += import_graph.get(rel_path, 0) * 5
        
        if role == 'entry_point':
            score += 10
        if is_likely_generated(rel_path, content):
            score -= 5
            
        scores[rel_path] = score
    return scores


def prioritize_files(files_metadata, scores, threshold=15):
    """
    Classifies files into categories:
    - 'detailed': High score or entry_point/core_logic/data_layer (needs individual LLM analysis)
    - 'cheap': Low score and has helper/test/config/routing role (uses predefined template)
    - 'batch': Similar files (e.g. UI components in the same folder) grouped together for one batch LLM call
    - 'ignored': Ignored from detailed summary (uses simple fallback)
    """
    classified = {}  # rel_path -> category ('detailed', 'cheap', 'batch', 'ignored')
    
    # Pre-classify markdown and very short files before other heuristics
    for f in files_metadata:
        rel_path = f['rel_path']
        ext = f['ext']
        if ext == '.md':
            classified[rel_path] = 'ignored'
            continue
        if f['lines'] < MIN_LINES_FOR_LLM:
            classified[rel_path] = 'cheap'
            continue

    # Pre-classify core files and cheap files
    for f in files_metadata:
        rel_path = f['rel_path']
        if rel_path in classified:
            continue
        role = get_file_role(rel_path)
        score = scores.get(rel_path, 0)
        
        # Rule: entry_point, core_logic, data_layer always get detailed analysis
        if role in ('entry_point', 'core_logic', 'data_layer'):
            classified[rel_path] = 'detailed'
        elif role in ('helper', 'test', 'config', 'routing') and score < threshold:
            classified[rel_path] = 'cheap'
            
    # Now group potential candidates for batching:
    # Files of the same extension in the same folder that are not already marked 'detailed' or 'cheap'
    # E.g. components/Button.tsx, components/Header.tsx
    folder_groups = {}  # (folder, ext) -> list of files
    for f in files_metadata:
        rel_path = f['rel_path']
        if rel_path in classified:
            continue
            
        ext = f['ext']
        # We only batch JS/TS/CSS/HTML style code files
        if ext not in ('.tsx', '.jsx', '.ts', '.js', '.css', '.html'):
            continue
            
        folder = os.path.dirname(rel_path)
        key = (folder, ext)
        folder_groups.setdefault(key, []).append(f)
        
    # Apply batching if group size >= 2
    batch_groups = []
    for (folder, ext), files in folder_groups.items():
        if len(files) >= 2:
            # We group them!
            group_files = []
            for f in files:
                rel_path = f['rel_path']
                classified[rel_path] = 'batch'
                group_files.append(rel_path)
            batch_groups.append(group_files)
            
    # The remaining unclassified files:
    # If score > threshold -> detailed
    # Else -> ignored (receives generic fallback description)
    for f in files_metadata:
        rel_path = f['rel_path']
        if rel_path in classified:
            continue
            
        score = scores.get(rel_path, 0)
        if score > threshold:
            classified[rel_path] = 'detailed'
        else:
            classified[rel_path] = 'ignored'
            
    return classified, batch_groups
